### ISSUE TITLE
Verze Nette

### ISSUE THREAD

**Issue by vaclavpavek** [nette/sandbox#72]
Bylo by možné do Sandboxu i Web-Project přidat verzi frameworku? Oba repositáře by měli mít informaci o verzi resp. na jaké verzi jsou založené.

**Comment by dg** [comment]
Verze jsou v composer.json https://github.com/nette/sandbox/blob/master/composer.json

**Comment by vaclavpavek** [comment]
myslel jsem něco na tento způsob https://github.com/nette/nette/blob/master/Nette/Framework.php
