### ISSUE TITLE
Isn't this insecure?

### ISSUE THREAD

**Issue by simPod** [nette/sandbox#77]
I was wondering whether it isn't insecure to tell user that the password is incorrect. Attacker can be sure he guess email correctly and now it's only password that remains to be guessed. Or is it there just for demonstration purposes?

![screen shot 2016-01-23 at 19 07 22](https://cloud.githubusercontent.com/assets/327717/12531949/a6ab375c-c207-11e5-93f4-4dc3c999883a.png)

**Comment by hrach** [comment]
Attacker can always try to register a new account and realize that the email is already occupied.

**Comment by simPod** [comment]
well...true story. Thanks

**Comment by enumag** [comment]
@hrach Only when you allow registration. Which you usually don't in AdminModule.

**Comment by hrach** [comment]
@enumag yeah, you are right. Still, the complexity of guessing the username is pretty low. Of course, you may disallow the better error nessage, but the security should be handled more in different layers: strong password requirements, https with proper encryption, 2FA, etc.

**Comment by enumag** [comment]
@hrach Agreed.

**Comment by fprochazka** [comment]
@simPod anyway, you shouldn't use the exception message as the message for the user

**Comment by simPod** [comment]
@fprochazka I'm using translation strings in exception messages that I sometimes add as error to the form. Is that a bad approach? What do you recommend?

**Comment by fprochazka** [comment]
@simPod well, if you generate message that doesn't have a translation, the translator will leak it, unless you have some kind of protection for that... Not very safe.

**Comment by fprochazka** [comment]
in this case, simple solution like this would be better

```php
try {
 // try login
} catch (AuthenticationException $e) {
    $form->addError('error.invalidCredentials');
}
```

**Comment by simPod** [comment]
@fprochazka ok so the point is that user shouldn't see the exception message I don't want him to see

**Comment by fprochazka** [comment]
@simPod exactly :)
