### ISSUE TITLE
ErrorPresenter doesn't work

### ISSUE THREAD

**Issue by medhi** [nette/sandbox#88]
- Installed sendbox with composer
- Set mode to production with `\Tracy\Debugger::enable(\Tracy\Debugger::PRODUCTION);` placed int `bootstrap.php`
- Modified `https://github.com/nette/sandbox/blob/master/app/presenters/templates/Error/500.phtml` (to recognize it when I see it)
- Test 1: manually threw `\Exception` in homepage presenter -> default nette 500 error shown
- Test 2: visited non existing page -> default nette 500 error shown

**Comment by dg** [comment]
To set mode to production use `$configurator->setDebugMode(FALSE)`.
